# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8868098739fd973ee4dc75311352ae0336715c29a1b6391e46390c7f2176804fda39decc100f3e452d703bf0228b42a8384b2976179b4eeb4a8e2beffda38472

test:
  secret_key_base: 5a744b77b0275df3a857b90f82c3371577ab8ec6fcebfa617465755564268505fad5185c727b39aebc6ee526cef11e7fa6cd351727d5a00d3b3bfad910a77f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7ba16bcb018d4e5403e3b4d6a74dbaf0ca6d17e0131bd1a7a764c61a006aeaa0646899f674f5d897da32a81fdf38170f2c25317f2327e78d64b8c41fe357bcb2
